export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'DEVELOPMENT';
export const TEST = 'TEST';
export const PRODUCTION = 'PRODUCTION';
export const USER_REPOSITORY = 'USER_REPOSITORY'
export const TASK_REPOSITORY = 'TASK_REPOSITORY'